export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_REQUEST_SUCCESS = 'CHECKOUT_REQUEST_SUCCESS';
export const CHECKOUT_REQUEST_FAILURE = 'CHECKOUT_REQUEST_FAILURE';

export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_REQUEST_SUCCESS = 'ADMIN_DELETE_PRODUCT_REQUEST_SUCCESS';
export const ADMIN_DELETE_PRODUCT_REQUEST_FAILURE = 'ADMIN_DELETE_PRODUCT_REQUEST_FAILURE';

export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST';
export const ADMIN_CREATE_PRODUCT_REQUEST_SUCCESS = 'ADMIN_CREATE_PRODUCT_REQUEST_SUCCESS';
export const ADMIN_CREATE_PRODUCT_REQUEST_FAILURE = 'ADMIN_CREATE_PRODUCT_REQUEST_FAILURE';

export const ADMIN_EDIT_PRODUCT_REQUEST = 'ADMIN_EDIT_PRODUCT_REQUEST';
export const ADMIN_EDIT_PRODUCT_REQUEST_SUCCESS = 'ADMIN_EDIT_PRODUCT_REQUEST_SUCCESS';
export const ADMIN_EDIT_PRODUCT_REQUEST_FAILURE = 'ADMIN_EDIT_PRODUCT_REQUEST_FAILURE';